name: caller-workflow
run-name: Run caller-workflow by ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
    uses: letsesign/called-workflow/.github/workflows/main.yml@fd69fb8b9e56e3638c58cdb44b590341e0f9dae7
